GM.PropList = {
    {"models/props_junk/wood_crate001a.mdl", 'Wooden Crate', 1},
    {"models/props_junk/wood_crate002a.mdl", 'Bigger Crate', 1},
    {"models/props_phx/construct/concrete_barrier00.mdl", 'Concrete Barrier A', 1},
    {"models/props_phx/construct/concrete_barrier01.mdl", 'Concrete Barrier B', 1},
    {"models/props_wasteland/interior_fence002d.mdl", 'Chain Fence', 1},
    {"models/props_lab/blastdoor001b.mdl", 'Blast Door', 1},
    {"models/props_interiors/VendingMachineSoda01a.mdl", 'Vending Machine', 1},
    {"models/props_debris/metal_panel02a.mdl", 'Sheet Metal', 1},
    {"models/props_building_details/Storefront_Template001a_Bars.mdl", 'Barred Doors', 1},
    {"models/props_combine/combine_barricade_short02a.mdl", 'Short Combine Barrier', 1},
    {"models/props_combine/combine_barricade_med01a.mdl", 'Medium Combine Barrier', 1},
    
    {"models/hunter/blocks/cube1x1x1.mdl", '1x1x1 Cube', 1},
    {"models/hunter/blocks/cube1x2x1.mdl", '1x2x1 Cube', 1},
    {"models/hunter/blocks/cube1x3x1.mdl", '1x3x1 Cube', 1},
    {"models/hunter/blocks/cube2x2x1.mdl", '2x2x1 Cube', 1},
    {"models/hunter/plates/plate2x2.mdl", '2x2 Plate', 1},
    {"models/hunter/plates/plate2x4.mdl", '2x4 Plate', 1},
    {"models/hunter/triangles/2x2.mdl", 'Triangle Plate', 1},
    {"models/hunter/geometric/pent1x1.mdl", 'Pentagon Plate', 1},
    {"models/hunter/geometric/hex1x1.mdl", 'Hexagon Plate', 1},
    {"models/hunter/tubes/circle2x2.mdl", 'Circle Plate', 1},
    {"models/hunter/triangles/trapezium.mdl", 'Trapezium Plate', 1},
    {"models/hunter/triangles/1x1x1.mdl", '1x1x1 Triangle', 1},
    {"models/hunter/triangles/2x1x1.mdl", '2x1x1 Triangle', 1},
    {"models/hunter/triangles/trapezium3x3x1.mdl", 'Full Trapezium', 1},
    {"models/hunter/triangles/trapezium3x3x1a.mdl", 'Half Trapezium', 1},
    {"models/hunter/triangles/trapezium3x3x1b.mdl", 'Quarter Trapezium', 1},
    {"models/hunter/triangles/trapezium3x3x1c.mdl", 'Slice Trapezium', 1},
    {"models/hunter/misc/squarecap1x1x1.mdl", 'Pyramid', 1},
    {"models/hunter/misc/stair1x1.mdl", 'Stairs', 1},
    {"models/hunter/misc/cone2x1.mdl", 'Cone', 1},
    {"models/hunter/misc/shell2x2a.mdl", 'Dome', 1},
    {"models/hunter/misc/shell2x2.mdl", 'Sphere', 1},
}